---
- name: Perform post-install configuration
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Change admin GUI password
      community.mysql.mysql_query:
        login_db: eve_ng_db
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        query: UPDATE users SET password = %(password)s WHERE username = 'admin';
        named_args:
          password: "{{ eve_password }}"

    - name: Disable initial configuration wizard
      file:
        path: /opt/ovf/.configured
        state: touch
        modification_time: preserve
        access_time: preserve
